@echo off
echo Starting BookFlow Backend Setup...

if not exist venv (
    echo Creating Python virtual environment...
    python -m venv venv
)

echo Activating virtual environment...
call venv\Scripts\activate.bat

echo Installing dependencies...
pip install -r requirements.txt

echo Starting Uvicorn Server...
python -m uvicorn main:app --port 8000 --reload
